/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected/organizations'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/_dashboard/index'
import { Route as ProtectedOrganizationsNewRouteImport } from './routes/_protected/organizations/new'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationsRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsNewRoute =
  ProtectedOrganizationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedOrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedDashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/organizations': typeof ProtectedOrganizationsRouteWithChildren
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedDashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/organizations': typeof ProtectedOrganizationsRouteWithChildren
  '/_protected/organizations/new': typeof ProtectedOrganizationsNewRoute
  '/_protected/_dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/organizations'
    | '/organizations/new'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/organizations/new' | '/organizations'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/organizations'
    | '/_protected/organizations/new'
    | '/_protected/_dashboard/'
    | '/_protected/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationsRoute
    }
    '/_protected/_dashboard/': {
      id: '/_protected/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations/new': {
      id: '/_protected/organizations/new'
      path: '/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof ProtectedOrganizationsNewRouteImport
      parentRoute: typeof ProtectedOrganizationsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedOrganizationsRouteChildren {
  ProtectedOrganizationsNewRoute: typeof ProtectedOrganizationsNewRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
}

const ProtectedOrganizationsRouteChildren: ProtectedOrganizationsRouteChildren =
  {
    ProtectedOrganizationsNewRoute: ProtectedOrganizationsNewRoute,
    ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  }

const ProtectedOrganizationsRouteWithChildren =
  ProtectedOrganizationsRoute._addFileChildren(
    ProtectedOrganizationsRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRouteWithChildren
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOrganizationsRoute: ProtectedOrganizationsRouteWithChildren,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
